---
name: Security
on:
    push:
        branches:
            - main
    pull_request: {}
    schedule:
    - cron: "0 0 * * *"
jobs:
    find-go-projects:
        runs-on: ubuntu-latest
        outputs:
            go-projects: ${{ steps.find-go-projects.outputs.go-projects }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - uses: actions/setup-go@v4
            with:
              cache: false
          - name: Find go projects
            id: find-go-projects
            run: |
              GO_PROJECTS=$(find . -name go.mod -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')
              echo "found go projects: $GO_PROJECTS"
              echo "go-projects=$GO_PROJECTS" >> "$GITHUB_OUTPUT"
    analyze:
        needs: find-go-projects
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                projects: ${{ fromJson( needs.find-go-projects.outputs.go-projects ) }}
        permissions:
            actions: read
            contents: read
            security-events: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: dorny/paths-filter@v2
              id: changes
              with:
                filters: |
                  project:
                    - ${{ matrix.projects }}/**
            - uses: actions/setup-go@v4
              with:
                go-version-file: ${{ matrix.projects }}/go.mod
                cache: false
            - name: Determine Golang cache paths
              id: go-env
              run: |
                echo "build-cache-path=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
                echo "module-cache-path=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
                echo "go-sum-file-path=${{ matrix.projects }}/go.sum" >>"$GITHUB_OUTPUT"
            - name: Setup Golang Cache
              uses: actions/cache@v3
              with:
                path: |
                  ${{ steps.go-env.outputs.build-cache-path }}
                  ${{ steps.go-env.outputs.module-cache-path }}
                key: ${{ runner.os }}-go-${{ hashFiles(steps.go-env.outputs.go-sum-file-path) }}
                restore-keys: |
                  ${{ runner.os }}-go-
            - uses: github/codeql-action/init@v3
              if: steps.changes.outputs.project == 'true'
              with:
                languages: go
                source-root: ${{ matrix.projects }}
                queries: security-extended,security-and-quality
            - uses: github/codeql-action/autobuild@v3
              if: steps.changes.outputs.project == 'true'
              with:
                working-directory: ${{ matrix.projects }}
            - uses: github/codeql-action/analyze@v3
              if: steps.changes.outputs.project == 'true'