---
name: Security
on:
    push:
        branches:
            - main
    pull_request: {}
    schedule:
    - cron: "0 0 * * *"
jobs:
    analyze:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                projects: ["project1", "project2"]
        permissions:
            actions: read
            contents: read
            security-events: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: dorny/paths-filter@v2
              id: changes
              with:
                filters: |
                  project:
                    - ${{ matrix.projects }}/**
            - uses: actions/setup-go@v4
              with:
                go-version: '1.21'
                cache-dependency-path: ${{ matrix.projects }}/go.sum
            - uses: github/codeql-action/init@v3
              if: steps.changes.outputs.project == 'true'
              with:
                languages: go
                source-root: ${{ matrix.projects }}
                queries: security-extended,security-and-quality
            - uses: github/codeql-action/autobuild@v3
              if: steps.changes.outputs.project == 'true'
              with:
                working-directory: ${{ matrix.projects }}
            - uses: github/codeql-action/analyze@v3
              if: steps.changes.outputs.project == 'true'