---
name: Security
on:
    push:
        branches:
            - main
    pull_request: {}
    schedule:
    - cron: "0 0 * * *"
jobs:
    analyze:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                projects: ["project1", "project2"]
        permissions:
            actions: read
            contents: read
            security-events: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: github/codeql-action/init@v3
              with:
                languages: go
                source-root: ${{ matrix.projects }}
                packs: codeql/go-all
            # - name: Build Project ${{ matrix.projects }}
            #   run: |
            #     set -x
            #     go build -o build -v ./${{ matrix.projects }}
            - uses: github/codeql-action/autobuild@v3
            - uses: github/codeql-action/analyze@v3
              with:
                category: "/language:go"
    
    